server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: protected_api_route
          uri: https://httpbin.org
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"